BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "room count" (
	"fabLab"	INTEGER,
	"lecture1"	INTEGER,
	"lecture2"	INTEGER,
	"scrum"	INTEGER,
	"caberet"	INTEGER,
	"meeting"	INTEGER,
	"VR"	INTEGER,
	"timeStamp"	TEXT NOT NULL UNIQUE,
	"item"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE
);
COMMIT;
