import React from 'react';

export default class About extends React.Component {
    constructor(props) {
        super(props);
    }
    render() {
        const content = {
            width: "90ch",
            margin: "100px auto"

        }
        return (
            <div style={content}>
                <h1>About Us</h1>

                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tempus mauris dui, ut ultrices odio luctus a. Nulla condimentum maximus lorem, nec porta nibh rutrum ut. Donec sollicitudin ligula risus, non egestas justo fringilla porttitor. Nullam quam ex, pellentesque vitae luctus eget, ultricies vel nibh. Donec eu ante eu enim bibendum ornare at a est. Curabitur mollis posuere lectus, sollicitudin suscipit sem rutrum vel. Integer dapibus ante vel mattis auctor. Nulla molestie congue diam sed hendrerit. Quisque bibendum magna eu nisi tempor volutpat. Quisque id metus convallis, dictum lacus sed, posuere orci. Nullam pharetra vitae nibh ac malesuada. Aliquam porta scelerisque lectus, eu aliquet leo viverra in. Sed consequat, magna et mattis faucibus, ligula quam ultrices nisl, a porta ante nibh eget nisl. Nunc lacinia mollis nunc, eu lacinia magna bibendum vel. Fusce vel eros sed lectus vestibulum posuere nec eget dolor.</p>
                <p>Morbi diam turpis, dictum non enim ac, fringilla ultricies eros. Nam consequat eleifend mauris, sed tempor urna dapibus sit amet. Vestibulum molestie metus eget mauris faucibus, nec convallis odio eleifend. Nullam gravida, augue a elementum viverra, risus sem facilisis velit, vel sagittis metus nisl sit amet enim. Morbi congue lectus quis mauris laoreet tempor. In commodo, justo vel pulvinar placerat, metus nunc blandit felis, non condimentum dui tellus eu ipsum. Nulla suscipit ullamcorper imperdiet. Pellentesque lobortis consectetur consectetur. Vivamus tristique molestie ligula, sit amet hendrerit lacus vulputate at. Pellentesque ac tincidunt ligula, quis cursus mauris. Morbi tincidunt id purus sed vestibulum. Aenean et massa consequat, elementum metus eu, euismod enim. Morbi viverra, justo quis varius dapibus, arcu magna facilisis felis, ut blandit nunc neque vitae arcu. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla facilisi.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam aliquam quam ut metus convallis mattis. Maecenas lacinia dolor vitae orci pharetra placerat. Quisque risus est, vestibulum eu dolor non, facilisis luctus tellus. Ut aliquam placerat risus, eget sollicitudin urna blandit in. Nam ultricies dui eu mollis dictum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur eu pharetra lacus. Vivamus posuere ullamcorper blandit. Aenean ultricies dui sit amet leo pretium hendrerit. Vestibulum eget orci mauris. Etiam hendrerit nisi turpis. Nunc ut commodo nibh.</p>
                <p>Phasellus viverra turpis ac egestas imperdiet. Nam tincidunt, magna vel elementum posuere, nunc elit tempor ipsum, sed bibendum nunc metus eu sapien. Praesent auctor auctor dictum. Nunc dignissim eros nunc, luctus gravida diam accumsan auctor. Morbi nec lorem purus. Vivamus vel quam sodales, finibus tellus ac, semper ligula. Morbi lobortis erat id mauris porta ultricies. Proin euismod, arcu at mattis tincidunt, neque mi iaculis eros, ac placerat elit enim at lorem. Curabitur suscipit imperdiet mi quis facilisis. Cras nec massa libero. Etiam dui nulla, sagittis id magna nec, mollis euismod lectus. Proin lacinia at ex et laoreet. Donec suscipit mauris vitae venenatis fringilla. Proin felis turpis, mollis eget lectus eget, ultrices tempor orci.</p>
                <p>Proin lacinia eleifend nisl, et laoreet metus aliquet facilisis. Fusce a mauris molestie, finibus ipsum id, tempor mi. Nullam laoreet molestie ex et molestie. Donec congue ipsum id velit ultrices vehicula. Cras blandit lorem diam, vitae semper massa bibendum et. Vestibulum tempor, tellus sit amet lacinia dapibus, nisi lectus pellentesque lorem, vitae congue nibh magna at augue. Donec at metus id neque vulputate sodales sit amet a dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi ut fermentum sem. Praesent imperdiet vestibulum ipsum, interdum cursus augue feugiat eget. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin vel quam nec ipsum interdum lobortis.</p>
                <p>Aliquam erat volutpat. Vestibulum mattis convallis justo, eget efficitur nulla. Aenean vitae turpis ut libero finibus fermentum non a nisi. Proin nisl nunc, cursus vitae velit vitae, pulvinar luctus est. Quisque eget sapien condimentum purus tempus lobortis ultrices ut justo. Nunc ultricies, elit quis pellentesque efficitur, eros mi rutrum lacus, sed vehicula tellus erat a turpis. Nunc blandit diam at pellentesque euismod. Vestibulum mollis lacinia nisl. Aenean vel neque arcu. Aliquam auctor, nisl quis fermentum tincidunt, magna ante aliquam quam, quis tristique massa eros et est. Nullam id leo non ipsum euismod fringilla eget non nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris egestas ornare pharetra. Aenean tempor risus nec urna posuere aliquam.</p>
                <p>Nulla eu bibendum sapien, sed tristique lacus. Integer malesuada eros in velit dapibus dignissim. Quisque id nisi est. Proin ut sagittis lorem, sed efficitur eros. Praesent turpis enim, rutrum a tortor vel, imperdiet euismod quam. Nam tincidunt quis lectus vel ullamcorper. Sed non nunc id nunc tincidunt suscipit a ac felis. Donec lacinia dui eget libero consectetur lobortis. Etiam tincidunt leo id purus interdum ullamcorper. Quisque faucibus lacinia ipsum quis volutpat. Proin iaculis hendrerit risus, sit amet venenatis felis venenatis eu. Ut ultrices auctor venenatis. Donec eu ultrices massa. Donec pharetra orci eu justo mattis egestas. Donec auctor sapien vel tortor faucibus, non maximus lorem condimentum.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed iaculis lobortis odio a dignissim. Pellentesque consequat consequat purus ac faucibus. Nam vitae lectus odio. Suspendisse et lectus a diam rutrum eleifend. Phasellus at malesuada nunc. Morbi nunc massa, porta sit amet sapien vitae, fermentum cursus leo. Aliquam erat volutpat. Pellentesque aliquam felis ut lacus vulputate tincidunt id vel risus.</p>
                <p>Proin bibendum tempus tristique. Integer in ex lorem. Vivamus tristique mauris velit, at euismod tortor lacinia non. Nulla pharetra cursus arcu, facilisis dictum est condimentum in. Suspendisse ultricies massa in ligula rutrum, ultrices bibendum metus blandit. Donec consectetur velit ac lacus fringilla cursus. Quisque in faucibus arcu, et porttitor dui. Sed eleifend purus id lobortis suscipit. Suspendisse accumsan id magna eget lacinia.</p>
                <p>Donec ac rutrum diam. Aliquam vel cursus arcu. Donec ligula tellus, porta ac malesuada vel, placerat sit amet neque. Etiam ullamcorper blandit orci nec mollis. Integer iaculis pharetra purus eget luctus. Donec a orci sit amet sem hendrerit porta. Cras at pretium nulla. Curabitur a lorem arcu. Sed vitae augue vitae justo viverra lobortis. Sed ut nisl at sapien sodales egestas. Maecenas hendrerit ac elit a gravida. Donec ultrices dolor ut dolor efficitur maximus. Sed hendrerit justo metus, at tempus risus laoreet ac. Fusce luctus eros lacinia magna malesuada, mollis sodales nibh molestie. Nam lobortis ex non erat rutrum rhoncus. Nunc fermentum imperdiet diam, ac tincidunt nibh sagittis nec. </p>
            </div>
        )
    }
}